name: Update README

on:
  schedule:
    - cron: '* 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://nothinux/github-pr:v0
