name: Update README

on:
  schedule:
    - cron: '* 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update readme
        run: |
          bin/github-pr README.md
          bin/push
